const links = [
    {
        title: "Introduccion a las matematicas",
        link: "https://n9.cl/matematicasproa",
        category: "matematica",
        tags: ["numeros reales", "operaciones basicas", "expresiones algebraicas", "polinomios", "regla de ruffini", "factorizacion", "divisibilidad", "racionalizacion", "ecuaciones de primer grado", "funcion lineal", "sistema de ecuaciones lineales", "ecuaciones de segundo grado", "funcion cuadratica", "ecuacion exponencial", "funcion exponencial", "funcion logaritmica", ],
    },
    {
        title: "Numeros y operaciones arimeticas",
        link: "https://n9.cl/matematicasproa3",
        category: "matematica",
        tags: ["numeros naturales", "numeros enteros", "numeros racionales", "propiedad conmutativa", "propiedad asociativa", "propiedad distributiva", "suma", "resta", "numeros reales", "funcion lineal", "ecuacion de primer grado", "ecuacion de segundo grado"], 
    },    
    {
        title: "Aritmetica basica",
        link: "https://n9.cl/matematicasproa4",
        category: "matematica",
        tags: ["numeros naturales", "numeros enteros", "numeros racionales", "numeros irracionales", "numeros reales", "suma", "resta", "multiplicacion", "asociativa", "conmutativa", "distributiva", "maximo comun multiplo", "minimo comun multiplo", "divisibilidad"], 
    },    
    {
        title: "Matematica polimodal",
        link: "https://n9.cl/matematicasproa6",
        category: "matematica",
        tags: ["numeros reales", "matrices", "expresiones algebraicas", "funciones", "ecuaciones", "numeros enteros", "numeros naturales", "numeros racionales", "recta real", "intervalo", "suma", "resta", "potenciacion", "division", "raiz", "radicacion", "funcion lineal", "dominio", "imagen", "inecuacion", "ecuaciones de primer grado", "ecuaciones de segundo grado"], 
    },
    {
        title: "Algebra y geometria",
        link: "https://n9.cl/matematicasproa7",
        category: "matematica",
        tags: ["matrices", "algebra", "geometria", "ecuacion lineal", "vectores"], 
    },
    {
        title: "Matematicas generales",
        link: "https://n9.cl/matematicasproa8",
        category: "matematica",
        tags: ["ecuaciones", "ecuacion vectorial", "rectas sectantes", "mediatriz", "numeros reales", "polinomios", "regla de ruffini", "logaritmos", "funcion derivada", "funcion raiz cuadrada", "limites de funciones polinomicas", "calculo de limites", "vectores", "bisectriz", "graficos", "tablas"], 
    },
    {
        title: "Prehistoria hasta la actualidad",
        link: "https://n9.cl/historiaproa",
        category: "historia",
        tags: ["historia argentina", "culturas aborigenes", "presidencias fundantes"],
    },
    {
        title: "Historia medieval",
        link: "https://n9.cl/historiaproa2",
        category: "historia",
        tags: ["epoca medieval", "edad media", "arte medieval", "periodo carolingio y otoniano"],
    },
    {
        title: "Historia mundial contemporanea",
        link: "https://n9.cl/historiaproa3",
        category: "historia",
        tags: ["sociedades burguesas", "sociedad liberal", "sociedad capitalista", "revolucion industrial", "revolucion francesa", "liberalismo", "segunda revolucion industrial", "imperialismo", "division internacional del trabajo", "revolucion rusa", "fascismo italiano", "nazismo", "primera guerra mundial", "segunda guerra mundial", "guerra civil española", "guerra fria", "mundo bipolar", "revolucion cubana", "neoliberalismo", "estado sovietico"],
    },
    {
        title: "Manual historia argentina",
        link: "https://n9.cl/historiaproa4",
        category: "historia",
        tags: ["iluminismo", "invasiones inglesas", "revolucion de mayo", "cabildo abierto", "unitarismo", "federalismo", "liga unitario", "pacto federal", ""],
    },    
    {
        title: "Historia del mundo contemporaneo",
        link: "https://n9.cl/historiaproa5",
        category: "historia belica",
        tags: ["El Imperialismo", "La Primera Guerra Mundial", "Revolucion Rusa", "Periodo Entreguerras en el ambito capitalista", "La Segunda Guerra Mundial y el Holocausto"],
    },
    {
        title: "historia conectar igualdad",
        link: "https://n9.cl/historiaproa6",
        category: "historia",
        tags: ["modelo agroexportador", "Globalizacion y Estados nacionales", "Civilizaciones antiguas latinoamericanas"],
    },
    {
        title: "historia argentina",
        link: "https://n9.cl/historia7",
        category: "historia",
        tags: ["argentina entre de 1810 y 1852"],
    },
    {
        title: "historia contemporanea",
        link: "https://n9.cl/historiaproa8",
        category: "historia",
        tags: ["politicas y dirigentes del pan", "juarez celman", "UCN", "UCR"],
    },
    {
        title: "historia epoca de rosas",
        link: "https://n9.cl/historiaproa9",
        category: "historia",
        tags: ["epoca de rosas", "la decada del 80", "argentina a principios del siglo 21"],
    },
    {
        title: "historia entre guerras",
        link: "https://n9.cl/georgeproa10",
        category: "historia",
        tags: ["capitalista y liberalista", "fin de la guerra fria"],
    },
    {
        title: "historia 1852 a 1890",
        link: "https://n9.cl/tomiproa11",
        category: "historia",
        tags: ["Urquiza", "Vencedor", "La revolucion"],
    },
    {
        title: "Vida de Lazarillo de Tormes",
        link: "",
        category: "literatura",
        tags: ["novela", "novela española", "anonima", "narrador-protagonista", "estilo epistolar", "autobiografia"],
    },
    {
        title: "Las aves",
        link: "",
        category: "literatura",
        tags: ["comedia clasica divertida", "comedia antigua", "comedia griega", "literatura griega"],
    },
    {
        title: "Poetica",
        link: "",
        category: "literatura",
        tags: ["reflexion estetica", "tragedia griega", "comedia antigua", "comedia griega"],
    },
    {
        title: "Orgullo y prejuicio",
        link: "",
        category: "literatura",
        tags: ["comedia romantica", "novela", "literatura inglesa", "narrador omnisciente", "narracion lineal"],
    },
    {
        title: "Sentido y sensibilidad",
        link: "",
        category: "literatura",
        tags: ["novela", "literatura inglesa", "literatu romantica", "narracion en tercera persona"],
    },
    {
        title: "Cumbres borrascosas",
        link: "",
        category: "literatura",
        tags: ["novela", "literatura inglesa", "ficcion gotica", "literatura victoriana", "novela gotica", "novela del romanticismo", "narracion en primera persona"],
    },
    {
        title: "Caperucita roja",  
        link: "",
        category: "literatura",
        tags: ["cuento", "literatura infantil", "cuento de hadas", "cuento con moraleja", "narrador homodiegetico"],
    },
    {
        title: "Llama de amor viva",
        link: "",
        category: "literatura",
        tags: ["poesia española", "poesia romantica", "narrativa poetica", "poesia mistica"],
    },
    {
        title: "Robinson Crusoe",
        link: "",
        category: "literatura",
        tags: ["aventura", "supervivencia", "autobiografia ficticia", "ficcion de aventuras", "narracion en primera persona"],
    },
    {
        title: "El jugador",
        link: "",
        category: "literatura",
        tags: ["novela rusa", "literatura rusa", "escenario europeo", "narracion en primera persona"],
    },
    
    {
        title: "Los hermanos Karamazov",
        link: "",
        category: "literatura",
        tags: ["novela rusa", "escenario ruso", "novela filosofica", "novela psicologica"],
    },
    {
        title: "Memorias del subsuelo",
        link: "",
        category: "literatura",
        tags: ["novela rusa", "literatura rusa", "ficcion filosofica", "escenario ruso", "narrador intradiegético"],
    },
    {
        title: "Las aventuras de Sherlock Holmes",
        link: "",
        category: "literatura",
        tags: ["cuento", "literatura inglesa", "ficcion de detectives", "cuento de aventuras", "cuento de suspenso"],
    }
]