const links = [
    {
        title: "Introducción a las matemáticas",
        link: "https://n9.cl/matematicasproa",
        category: "matemática",
        tags: ["números reales", "operaciones básicas", "expresiones algebraicas", "polinomios", "regla de ruffini", "factorizacion", "divisibilidad", "racionalizacion", "ecuaciones de primer grado", "funcion lineal", "sistema de ecuaciones lineales", "ecuaciones de segundo grado", "funcion cuadratica", "ecuacion exponencial", "funcion exponencial", "funcion logaritmica", ],
    },
    {
        title: "Números y operaciones aritméticas",
        link: "https://n9.cl/matematicasproa3",
        category: "matemática",
        tags: ["números naturales", "números enteros", "números racionales", "propiedad conmutativa", "propiedad asociativa", "propiedad distributiva", "suma", "resta", "números reales", "función lineal", "ecuación de primer grado", "ecuación de segundo grado"], 
    },
    {
        title: "Aritmética básica",
        link: "https://n9.cl/matematicasproa4",
        category: "matemática",
        tags: ["números naturales", "números enteros", "números racionales", "números irracionales", "números reales", "suma", "resta", "multiplicación", "asociativa", "conmutativa", "distributiva", "maximo común multiplo", "mínimo común multiplo", "divisibilidad"], 
    },
    {
        title: "Matemática polimodal",
        link: "https://n9.cl/matematicasproa6",
        category: "matemática",
        tags: ["números reales", "matrices", "expresiones algebraicas", "funciones", "ecuaciones", "números enteros", "números naturales", "números racionales", "recta real", "intervalo", "suma", "resta", "potenciacion", "division", "raiz", "radicacion", "funcion lineal", "dominio", "imagen", "inecuacion", "ecuaciones de primer grado", "ecuaciones de segundo grado"], 
    },
    {
        title: "Álgebra y geometría",
        link: "https://n9.cl/matematicasproa7",
        category: "matemática",
        tags: ["matrices", "algebra", "geometria", "ecuación lineal", "vectores"], 
    },
    {
        title: "Matemáticas generales",
        link: "https://n9.cl/matematicasproa8",
        category: "matemática",
        tags: ["ecuaciones", "ecuacion vectorial", "rectas sectantes", "mediatriz", "números reales", "polinomios", "regla de ruffini", "logaritmos", "funcion derivada", "funcion raiz cuadrada", "limites de funciones polinomicas", "calculo de limites", "vectores", "bisectriz", "graficos", "tablas"], 
    },
    {
        title: "Prehistoria hasta la actualidad",
        link: "https://n9.cl/historiaproa",
        category: "historia",
        tags: ["historia argentina", "culturas aborígenes", "presidencias fundantes"],
    },
    {
        title: "Historia medieval",
        link: "https://n9.cl/historiaproa2",
        category: "historia",
        tags: ["epoca medieval", "edad media", "arte medieval", "periodo carolingio y otoniano"],
    },
    {
        title: "Historia mundial contemporánea",
        link: "https://n9.cl/historiaproa3",
        category: "historia",
        tags: ["sociedades burguesas", "sociedad liberal","sociedad capitalista", "revolucion industrial", "revolucion francesa", "liberalismo", "segunda revolucion industrial", "imperialismo", "division internacional del trabajo", "revolucion rusa", "fascismo italiano", "nazismo", "primera guerra mundial", "segunda guerra mundial", "guerra civil española", "guerra fria", "mundo bipolar", "revolucion cubana", "neoliberalismo", "estado sovietico"],
    },
    {
        title: "Manual historia Argentina",
        link: "https://n9.cl/historiaproa4",
        category: "historia",
        tags: ["iluminismo", "invasiones inglesas", "revolucion de mayo", "cabildo abierto", "unitarismo", "federalismo", "liga unitario", "pacto federal", ""],
    },    
    {
        title: "Historia del mundo contemporáneo",
        link: "https://n9.cl/historiaproa5",
        category: "historia",
        tags: ["El Imperialismo", "La Primera Guerra Mundial y la Revolución Rusa", "Período Entreguerras en el ámbito capitalista", "La Segunda Guerra Mundial y el Holocausto"],
    },
    {
        title: "Historia conectar igualdad",
        link: "https://n9.cl/historiaproa6",
        category: "historia",
        tags: ["modelo agroexportador", "Globalización y Estados nacionales", "Civilizaciones antiguas latinoamericanas"],
    },
    {
        title: "Historia normal",
        link: "https://n9.cl/historia7",
        category: "historia",
        tags: ["Argentina entre 1810 y 1852"],
    },
    {
        title: "Historia contemporánea",
        link: "https://n9.cl/historiaproa8",
        category: "historia",
        tags: ["políticas y dirigentes del pan", "juares celma", "UCN y UCR"],
    },
    {
        title: "Historia época de Rosas",
        link: "https://n9.cl/historiaproa9",
        category: "historia",
        tags: ["epoca de rosas", "la decada del 80", "Argentina a principios del siglo 21"],
    },
    {
        title: "Historia entre guerras",
        link: "https://n9.cl/georgeproa10",
        category: "historia",
        tags: ["capitalista y liberalista", "fin de la guerra fria"],
    },
    {
        title: "Historia 1852 a 1890",
        link: "https://n9.cl/tomiproa11",
        category: "historia",
        tags: ["Urquiza", "el vencedor", "La revolución"],
    },
    {
        title: "Vida de Lazarillo de Tormes",
        link: "https://drive.google.com/file/d/1qJiiNR6lRwvloIAfQDtjvdtgyzcmwv7l/view?usp=sharing",
        category: "literatura",
        tags: ["novela", "novela española", "anonima", "narrador-protagonista", "estilo epistolar", "autobiografia"],
    },
    {
        title: "Las aves",
        link: "https://drive.google.com/file/d/1qrM50bSbrV4uogNCkni37znN8hWsW36M/view?usp=sharing",
        category: "literatura",
        tags: ["comedia clasica divertida", "comedia antigua", "comedia griega", "literatura griega"],
    },
    {
        title: "Poética",
        link: "https://drive.google.com/file/d/1qS5iUqq5Cb79F09I3xYpxGwFHLJQawBu/view?usp=sharing",
        category: "literatura",
        tags: ["reflexion estetica", "tragedia griega", "comedia antigua", "comedia griega"],
    },
    {
        title: "Orgullo y prejuicio",
        link: "https://drive.google.com/file/d/1qq_3_yVGSN1HuU0aupxubndOxRug_EG-/view?usp=sharing",
        category: "literatura",
        tags: ["comedia romantica", "novela", "literatura inglesa", "narrador omnisciente", "narracion lineal"],
    },
    {
        title: "Sentido y sensibilidad",
        link: "https://drive.google.com/file/d/1qp31pehtPRJQWUekY0DEmbSKeAFBPPJy/view?usp=sharing",
        category: "literatura",
        tags: ["novela", "literatura inglesa", "literatu romantica", "narracion en tercera persona"],
    },
    {
        title: "Cumbres borrascosas",
        link: "https://n9.cl/chichaneta",
        category: "literatura",
        tags: ["novela", "literatura inglesa", "ficcion gotica", "literatura victoriana", "novela gotica", "novela del romanticismo", "narracion en primera persona"],
    },
    {
        title: "Caperucita roja",  
        link: "https://drive.google.com/file/d/1qsQnM9VNJU9opSv4i4swiMkyZG07Q1ka/view?usp=sharing",
        category: "literatura",
        tags: ["cuento", "literatura infantil", "cuento de hadas", "cuento con moraleja", "narrador homodiegetico"],
    },
    {
        title: "Llama de amor viva",
        link: "https://drive.google.com/file/d/1qsQnM9VNJU9opSv4i4swiMkyZG07Q1ka/view?usp=sharing",
        category: "literatura",
        tags: ["poesia española", "poesia romantica", "narrativa poetica", "poesia mistica"],
    },
    {
        title: "Robinson Crusoe",
        link: "https://drive.google.com/file/d/1qsYeiEdmL0z3amljsIVrSYhr7QSnaWFf/view?usp=sharing",
        category: "literatura",
        tags: ["aventura", "supervivencia", "autobiografia ficticia", "ficcion de aventuras", "narracion en primera persona"],
    },
    {
        title: "El jugador",
        link: "https://drive.google.com/file/d/1qmVTwFrtEQeMgc7AcM5eshAa9lJftrOJ/view?usp=sharing",
        category: "literatura",
        tags: ["novela rusa", "literatura rusa", "escenario europeo", "narracion en primera persona"],
    },
    {
        title: "Los hermanos Karamazov",
        link: "https://drive.google.com/file/d/1quK6il3-tPbB9Tz7kj2bEPV7V5cC49MZ/view?usp=sharing",
        category: "literatura",
        tags: ["novela rusa", "escenario ruso", "novela filosofica", "novela psicologica"],
    },
    {
        title: "Memorias del subsuelo",
        link: "https://drive.google.com/file/d/1qOkvZ7xQtiid03ogU8NlCypgYB65yqTV/view?usp=sharing",
        category: "literatura",
        tags: ["novela rusa", "literatura rusa", "ficcion filosofica", "escenario ruso", "narrador intradiegético"],
    },
    {
        title: "Las aventuras de Sherlock Holmes",
        link: "https://drive.google.com/file/d/1qeIk6TMmmDVTPM2LYjzJm4h1EfnkTb7X/view?usp=sharing",
        category: "literatura",
        tags: ["cuento", "literatura inglesa", "ficcion de detectives", "cuento de aventuras", "cuento de suspenso"],
    },
    {
        title: "El conde de Montecristo",
        link: "https://drive.google.com/file/d/1quscmWOgpGNwacHEI5gu9RPjyss9MUiY/view?usp=sharing",
        category: "literatura",
        tags: ["novela", "novela de aventuras", "novela clasica", "ficcion romantica", "ficcion de aventuras", "ficcion historica"],
    },
    {
        title: "El tulipán negro",
        link: "https://drive.google.com/file/d/1q8puoY6SgmtazEoKUpICqjvIZ_v9OKOW/view?usp=sharing",
        category: "literatura",
        tags: ["novela", "novela historica", "novela cortes", "ficcion historica"],
    },
    {
        title: "Los tres mosqueteros",
        link: "https://drive.google.com/file/d/1qCFGuHhhw96jFFDrSG6EQ_lBdDTJGToP/view?usp=sharing",
        category: "literatura",
        tags: ["novela", "novela de capa y espada", "novela historica", "novela de aventuras"],
    },
    {
        title: "Días y Noches de Amor y de Guerra",
        link: "https://drive.google.com/file/d/19aqqAq-dpTNctNcJxS5BwDiBFVvgnrCp/view?usp=sharing",
        category: "literatura",
        tags: ["novela de amor", "lacrimogeno testimonio", "novela de drama", "novela en periodo de conflicto"],
    },
    {
        title: "El libro de los abrazos",
        link: "https://drive.google.com/file/d/1p09VKAjHtt3WF97fADxhy_gQRfTthVAA/view?usp=sharing",
        category: "literatura",
        tags: ["poesia epica", "latinoamerica", "literatura social"],
    },
    {
        title: "Patas arriba: La escuela del mundo al revés",
        link: "https://drive.google.com/file/d/1MSoTqtcpjmVoqcnm9-HwMX9ljjzzEQTe/view?usp=sharing",
        category: "literatura",
        tags: ["literatura critica", "literatura social", "literatura narrativa"],
    },
    {
        title: "Los troyanos",
        link: "https://drive.google.com/file/d/1qgYNVYj0vYl8ASMfO5LB6poB_C_dkXvp/view?usp=sharing",
        category: "literatura",
        tags: ["tragedia", "literatura griega", "drama saritico", "tetralogia"],
    },
    {
        title: "Medea",
        link: "https://drive.google.com/file/d/1r0LOqghiT6qY7oU_Z74XvKafwBANC3Oc/view?usp=sharing",
        category: "literatura",
        tags: ["tragedia", "literatura griega", "tetralogia", "drama saritico"],
    },
    {
        title: "Madame bovary",
        link: "https://drive.google.com/file/d/1q86eRkBVudt568GDbxIru3hRFmmM6m5n/view?usp=sharing",
        category: "literatura",
        tags: ["novela", "novela realista", "literatura francesa", "realismo"],
    },
    {
        title: "Cien años de soledad",
        link: "https://drive.google.com/file/d/1BAfQFjlmnCKv4sNpMcEPo8HCxw3Dhfdl/view?usp=sharing",
        category: "literatura",
        tags: ["novela", "narracion", "realismo magico", "literatura hispanoamerica", "literatura universal"],
    },
    {
        title: "La casa inundada",
        link: "https://drive.google.com/file/d/1qAppBdmT76K2sR2PcWQMCGOWHWtNsn0l/view?usp=sharing",
        category: "literatura",
        tags: ["novela de trama"],
    },
    {
        title: "El conde Lucanor",
        link: "https://drive.google.com/file/d/1qQOw-Ku6udEUjy9L9qJpG2JH7MppLyNg/view?usp=sharing",
        category: "literatura",
        tags: ["cuento de drama", "cuento"],
    },
    {
        title: "El castillo",  
        link: "https://drive.google.com/file/d/1qypigAmo33gI0NkBFoOPNqM7azEo26ux/view?usp=sharing",
        category: "literatura",
        tags: ["novela ficticia"],
    },
    {
        title: "Buzón de tiempo",
        link: "https://drive.google.com/file/d/1qypigAmo33gI0NkBFoOPNqM7azEo26ux/view?usp=sharing",
        category: "literatura",
        tags: ["novela de amor y romance"],
    }
];
